// scripts/validate.js — THE unified regression harness for every mechanic
// detection module, replacing the old per-mechanic validate-<mechanic>.js
// scripts (which were ten near-identical copies of the same loop).
//
// Usage (from the repo root):
//   node scripts/validate.js                          # every mechanic, every report
//   node scripts/validate.js forsaken                 # one mechanic, every report
//   node scripts/validate.js forsaken blackhole       # several mechanics
//   node scripts/validate.js sampledata/ff/<code>     # every mechanic, one report
//   node scripts/validate.js stompies sampledata/ff/<code>
//   node scripts/validate.js --check                  # diff output vs expectations/
//   node scripts/validate.js --update                 # regenerate expectations/
//   node scripts/validate.js --prune                  # drop snapshots whose sampledata is gone
//   node scripts/validate.js --list                   # print mechanic names
//
// Args that match a mechanic name select mechanics; anything else is treated
// as a report folder path. With no folder args, every report folder under
// sampledata/ff/ and sampledata/wow/ (any subdirectory containing a
// meta.json, as produced by scripts/fetch-{ff,wow}-report.js) is processed.
//
// ── Expected-output baselines (expectations/, gitignored like sampledata) ──
//
// expectations/ holds log-derived data (real player names, error text), so
// like sampledata/ it stays out of git — it's a local development tool, not
// part of the codebase. A snapshot is only meaningful while its report's
// sampledata exists (without the data, detection can't re-run, so the
// snapshot can never fail again): when a report folder is deleted to free
// space, its snapshot is dead weight — --check/--update warn about such
// orphans, and `node scripts/validate.js --prune` deletes them. Before
// deleting a report, make sure anything it UNIQUELY proved is encoded
// durably (threshold comments with clean/failure extremes, README rules,
// rulings) — the snapshot itself is never the long-term record. Two tiers:
//
// 1. SNAPSHOTS — expectations/<game>-<reportCode>.json, machine-generated by
//    --update. `--check` re-runs detection and reports every added/removed/
//    changed error vs the snapshot. Snapshots are a *reviewed baseline*, not
//    eternal truth: when detection philosophy evolves intentionally (e.g. a
//    severity downgrade), the workflow is: make the change, run --check to
//    confirm the delta is exactly what was intended and nothing else, then
//    --update and commit — the git diff of the snapshot IS the review
//    artifact. Narrowed runs (mechanic and/or report args) check/update only
//    the narrowed subset, merging into existing snapshot files.
//
// 2. RULINGS — expectations/rulings.json, small and hand-curated: specific
//    adjudications the user made during VOD review ("pull 15: only X should
//    flag", "pull 10: Y must NOT flag clipped-by-neighbor"). Checked on
//    every --check run but NEVER touched by --update — a ruling violation
//    means the change contradicts a call the user personally made, and the
//    ruling must be consciously edited (or the change reconsidered), never
//    silently regenerated away. Severity-only philosophy shifts don't touch
//    rulings at all (a ruling pins who flags, not how severely).
//
// mitigation-analysis is sanity-print only and contributes nothing to
// snapshots; cross-pull summary sections (Black Hole strategy, kick order,
// crystal assignments, Graven layout) are printed but not snapshotted —
// only PullErrors are.
//
// Each mechanic entry in MECHANICS below declares which game it belongs to,
// how to load its detection module(s) (transpiled on the fly from .ts via
// scripts/lib/require-ts.js), and how to run it over one report. Per-pull
// inputs (PlayerInfo[]/DeathEvent[]/etc.) are built once per report through
// a lazy, memoized pull context and shared across all selected mechanics —
// running everything is barely more expensive than running one.
//
// Two timestamp conventions coexist, matching the live pipeline exactly:
// most FF modules receive raw absolute report-ms timestamps, but phase1 and
// graven-image gate on fight-relative windows and receive streams shifted by
// the pull's own earliest event (same as log-transforms.ts's fightStart).
// WoW pulls are always fight-relative (build-wow-players.js shifts them).
//
// No verified expected-results table exists yet for the current sample
// captures — this harness's role is regression protection (no crashes, no
// warnings) plus a readable per-pull error summary to eyeball after any
// mechanic change. Also run `npx tsc --noEmit`.
const fs = require('fs');
const path = require('path');
const { ROOT, requireTsFromRoot } = require('./lib/require-ts');
const { discoverReportFolders, loadReportFolder, buildActorMap, buildAbilityMap, STREAM_KEYS } = require('./lib/load-report-folder');
const ffb = require('./lib/build-ff-players');
const { buildWowPull } = require('./lib/build-wow-players');

// ── shared helpers ──────────────────────────────────────────────────────────

// phase1.ts / graven-image.ts gate on fight-relative time windows (matching
// the real pipeline, where every timestamp is already event.timestamp -
// fightStart) — but load-report-folder's raw streams keep absolute report-ms
// timestamps. Shift every stream by this pull's own earliest event.
function toFightRelative(rep) {
  const allTimestamps = STREAM_KEYS.flatMap((k) => (rep[k]?.data ?? []).map((e) => e.timestamp));
  const fightStart = Math.min(...allTimestamps);
  const shifted = {};
  for (const key of STREAM_KEYS) {
    shifted[key] = { data: (rep[key]?.data ?? []).map((e) => ({ ...e, timestamp: e.timestamp - fightStart })) };
  }
  return shifted;
}

// Approximates Pull.fightDuration (real pipeline: fight.endTime -
// fight.startTime from the WCL/FFLogs fight metadata) from the raw event
// streams themselves — max minus min timestamp across every stream. This
// harness never loads meta.json's fights array, so this is the only
// duration signal available; it undercounts slightly (no events fire in
// the last instant before a wipe/kill) but that's negligible against the
// multi-minute thresholds anything here gates on (see wave-cannon.ts).
// `ignore`: streams left out. WoW leaves out the damage analysis's
// playerBuffs/enemyDebuffs (added 2026-10-06), whose edge events shifted
// mechanic timings by ~0.1s; FFXIV baselines were built with them counted.
function fightDurationMs(rep, ignore = new Set()) {
  // Loop, not Math.max(...spread): large WoW pulls exceed the call-stack
  // argument limit.
  let min = Infinity, max = -Infinity;
  for (const k of STREAM_KEYS) {
    if (ignore.has(k)) continue;
    for (const e of (rep[k]?.data ?? [])) {
      if (e.timestamp < min) min = e.timestamp;
      if (e.timestamp > max) max = e.timestamp;
    }
  }
  return max - min;
}

// Lazy, memoized per-pull input builders so pulls are only transformed for
// the streams a selected mechanic actually needs, and only once per report
// no matter how many mechanics run.
function makeFFPullCtx(pull, actorMap, abilityMap, getFFJobByName) {
  const cache = new Map();
  const memo = (key, fn) => {
    if (!cache.has(key)) cache.set(key, fn());
    return cache.get(key);
  };
  const rel = () => memo('rel', () => toFightRelative(pull.rep));
  return {
    bossName: pull.bossName,
    pullNumber: pull.pullNumber,
    fightDurationMs: () => memo('fightDurationMs', () => fightDurationMs(pull.rep)),
    players:         () => memo('players', () => ffb.buildFFPlayers(pull.rep, actorMap, getFFJobByName, abilityMap)),
    deaths:          () => memo('deaths', () => ffb.buildFFDeaths(pull.rep, actorMap, getFFJobByName)),
    enemyCasts:      () => memo('enemyCasts', () => ffb.buildFFEnemyCastEvents(pull.rep, actorMap, abilityMap)),
    geometry:        () => memo('geometry', () => ffb.buildFFBlackHoleGeometry(pull.rep, actorMap, abilityMap)),
    puddleSamples:   () => memo('puddleSamples', () => ffb.buildFFStompiesPuddleSamples(pull.rep, actorMap, abilityMap)),
    positionSamples: () => memo('positionSamples', () => ffb.buildFFPlayerPositionSamples(pull.rep, actorMap)),
    relPlayers:      () => memo('relPlayers', () => ffb.buildFFPlayers(rel(), actorMap, getFFJobByName, abilityMap)),
    relDeaths:       () => memo('relDeaths', () => ffb.buildFFDeaths(rel(), actorMap, getFFJobByName)),
    relEnemyCasts:   () => memo('relEnemyCasts', () => ffb.buildFFEnemyCastEvents(rel(), actorMap, abilityMap)),
    relStateSignals: () => memo('relStateSignals', () => ffb.buildFFKefkaSaysStateSignals(rel(), actorMap)),
  };
}

// WoW pull inputs (a WowPullContext, see lib/mechanics/wow/common.ts), built
// once per pull and shared by every WoW mechanic — the live pipeline hands
// all modules the same objects too. Keyed on the pull object, so a report's
// contexts are freed once the driver moves on to the next report.
const wowPullCache = new WeakMap();
const WOW_DURATION_IGNORED_STREAMS = new Set(['playerBuffs', 'enemyDebuffs']);
function wowPullContext(pull, actorMap, abilityMap, getSpecInfo) {
  if (!wowPullCache.has(pull)) {
    const built = buildWowPull(pull.rep, actorMap, abilityMap, getSpecInfo);
    wowPullCache.set(pull, { ...built, pullDurationMs: fightDurationMs(pull.rep, WOW_DURATION_IGNORED_STREAMS) });
  }
  return wowPullCache.get(pull);
}

function printPullErrors(ctx, errors, extraLists = []) {
  const all = [...errors, ...extraLists.flatMap(([, list]) => list)];
  const extraSummary = extraLists.map(([label, list]) => `, ${list.length} ${label}`).join('');
  console.log('='.repeat(70));
  console.log(`${ctx.bossName} Pull ${ctx.pullNumber} ->`, errors.length, 'errors' + extraSummary);
  for (const e of all) {
    console.log(`  [${e.ruleId}] t=${e.timestamp} ${e.player ?? '(raid)'}: ${e.description}`);
  }
  recordErrors(ctx.bossName, ctx.pullNumber, all);
}

// ── snapshot recording ──────────────────────────────────────────────────────
//
// Every runner funnels its PullErrors through recordErrors (printPullErrors
// does it automatically; the midnightfalls runner calls it
// directly since their print formats differ). The driver collects entries
// per report for --check / --update.
let currentMechanic = null;
let currentEntries = null;

function recordErrors(bossName, pullNumber, errors) {
  if (!currentEntries) return;
  for (const e of errors) {
    currentEntries.push({
      mechanic: currentMechanic,
      boss: bossName ?? null,
      pull: pullNumber ?? null,
      ruleId: e.ruleId ?? null,
      severity: e.severity ?? null,
      player: e.player ?? null,
      t: e.timestamp ?? null,
      name: e.name ?? null,
      description: e.description ?? null,
    });
  }
}

// Deterministic ordering so snapshot files diff minimally in git.
function sortEntries(entries) {
  const k = (e) => [e.mechanic, e.boss, String(e.pull).padStart(4, '0'), String(e.t).padStart(12, '0'), e.ruleId, e.player, e.description].join('|');
  return [...entries].sort((a, b) => k(a) < k(b) ? -1 : k(a) > k(b) ? 1 : 0);
}

// ── mechanic manifest ───────────────────────────────────────────────────────
//
// game: 'ff' | 'wow' — which sampledata/ subtree the mechanic runs against.
// load(): transpile + return the detection module(s); called once, lazily.
// run({ mod, ctxs, ... }): process ONE report and print its results.
//   FF entries get `ctxs` (one lazy pull context per pull, see above);
//   WoW entries share one memoized context per pull (wowPullContext), and
//   most are generated from lib/mechanics/wow/registry.ts (see
//   addWowRegistryEntries); mitigation-analysis goes through the
//   real app pipeline (lib/sample-report-store.ts + lib/log-transforms.ts)
//   instead, because it needs properly-resolved ability names — so it loads
//   the report itself by code and only works for folders under sampledata/.

const MECHANICS = {
  // The declarative single-ability table (lib/error-rules.ts) run through the
  // real evaluator. Not a "mechanic" module, but it produces PullErrors the
  // same way and had no regression coverage at all before — which mattered
  // once Damage Down grew a blameless-cause exclusion list.
  rules: {
    game: 'ff',
    load: () => requireTsFromRoot('lib/error-detection.ts'),
    run({ mod, ctxs }) {
      for (const c of ctxs) printPullErrors(c, mod.detectPullErrors(c.relPlayers(), c.relDeaths(), c.relEnemyCasts()));
    },
  },

  forsaken: {
    game: 'ff',
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/forsaken.ts'),
    run({ mod, ctxs }) {
      for (const c of ctxs) printPullErrors(c, mod.detectForsakenTowerErrors(c.players(), c.deaths(), c.enemyCasts()));
    },
  },

  limitcut: {
    game: 'ff',
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/limitcut.ts'),
    run({ mod, ctxs }) {
      for (const c of ctxs) printPullErrors(c, mod.detectLimitCutErrors(c.players(), c.deaths()));
    },
  },

  exdeath: {
    game: 'ff',
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/exdeath.ts'),
    run({ mod, ctxs }) {
      for (const c of ctxs) printPullErrors(c, mod.detectExdeathErrors(c.players(), c.deaths()));
    },
  },

  'kefka-says': {
    game: 'ff',
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/kefka-says.ts'),
    run({ mod, ctxs }) {
      for (const c of ctxs) printPullErrors(c, mod.detectKefkaSaysErrors(c.relPlayers(), c.relDeaths(), c.relEnemyCasts(), c.relStateSignals()));
    },
  },

  phase1: {
    game: 'ff',
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/phase1.ts'),
    run({ mod, ctxs }) {
      for (const c of ctxs) printPullErrors(c, mod.detectPhase1Errors(c.relPlayers(), c.relDeaths(), c.relEnemyCasts()));
    },
  },

  'ultimate-kefka': {
    game: 'ff',
    lateCapture: true, // Phase 5 only — safe on --from-minutes captures (see isLateCapture)
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/ultimate-kefka.ts'),
    run({ mod, ctxs }) {
      for (const c of ctxs) printPullErrors(c, mod.detectUltimateKefkaErrors(c.relPlayers(), c.relDeaths(), c.relEnemyCasts()));
    },
  },

  stompies: {
    game: 'ff',
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/stompies.ts'),
    run({ mod, ctxs }) {
      for (const c of ctxs) {
        printPullErrors(c, mod.detectStompiesErrors(c.players(), c.deaths(), c.enemyCasts(), c.geometry(), c.puddleSamples(), c.positionSamples()));
      }
    },
  },

  blackhole: {
    game: 'ff',
    load: () => ({
      ...requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/blackhole.ts'),
      ...requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/blackhole-strategy.ts'),
    }),
    run({ mod, ctxs }) {
      // Pull-like objects — the minimum the cross-pull strategy analysis
      // needs — built once so it sees every pull in the report, same as the
      // app's page.tsx does over its live `pulls` state.
      const pullLikes = ctxs.map((c) => ({
        game: 'ffxiv',
        players: c.players(),
        deathEvents: c.deaths(),
        blackHoleGeometry: c.geometry(),
        bossName: c.bossName, pullNumber: c.pullNumber,
      }));

      const strategy = mod.detectBlackHoleStrategy(pullLikes);
      if (strategy) {
        console.log('-'.repeat(70));
        console.log(`  Black Hole strategy: ${strategy.strategyId} (shape: ${strategy.shape}, from ${strategy.pullsAnalyzed} pull(s))`);
        for (const lane of strategy.lanes) {
          console.log(`    ${lane.slotLabel.padEnd(20)} ${lane.player} (${lane.className}) -> tethers ${lane.moments.join(',')}`);
        }
      } else {
        console.log('  Black Hole strategy: not enough recognized-composition pulls to resolve');
      }

      for (const p of pullLikes) {
        printPullErrors(p, mod.detectBlackHoleErrors(p.players, p.deathEvents), [
          ['missed-assigned-tether', mod.detectMissedAssignedTetherErrors(p, strategy)],
          ['clipped-by-neighbor',    mod.detectClippedByNeighborTetherErrors(p, strategy)],
          ['incorrect-direction',    mod.detectIncorrectBlackHoleDirectionErrors(p, strategy)],
        ]);
      }
    },
  },

  'graven-image': {
    game: 'ff',
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/graven-image.ts'),
    run({ mod, ctxs }) {
      // Cross-pull: learns the report's own layout from ALL its pulls, then
      // checks each pull against it. Fight-relative, like phase1.
      const pullLikes = ctxs.map((c) => ({
        game: 'ffxiv',
        players: c.relPlayers(),
        deathEvents: c.relDeaths(),
        bossName: c.bossName, pullNumber: c.pullNumber,
      }));

      const layout = mod.learnGravenImageLayout(pullLikes);
      console.log('-'.repeat(70));
      console.log('  Learned layout:');
      for (const [className, { north, south }] of Object.entries(layout)) {
        console.log(`    ${className.padEnd(12)} north=${north ? `${north.x},${north.y}` : '—'}  south=${south ? `${south.x},${south.y}` : '—'}`);
      }

      for (const p of pullLikes) {
        printPullErrors(p, mod.detectGravenImageSpreadErrors(p, layout), [
          ['stack', mod.detectGravenImageStackErrors(p)],
        ]);
      }
    },
  },

  'wave-cannon': {
    game: 'ff',
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/wave-cannon.ts'),
    run({ mod, ctxs }) {
      // Cross-pull: learns the report's own layout from its long (2+ min)
      // pulls only, then checks each pull against it. Fight-relative, like
      // phase1/graven-image.
      const pullLikes = ctxs.map((c) => ({
        fightDuration: c.fightDurationMs(),
        players: c.relPlayers(),
        deathEvents: c.relDeaths(),
        bossName: c.bossName, pullNumber: c.pullNumber,
      }));

      const layout = mod.learnWaveCannonLayout(pullLikes);
      console.log('-'.repeat(70));
      console.log('  Learned layout:');
      for (const [className, spot] of Object.entries(layout)) {
        console.log(`    ${className.padEnd(12)} ${spot ? `${spot.x},${spot.y}` : '—'}`);
      }

      for (const p of pullLikes) {
        printPullErrors(p, mod.detectWaveCannonPositionErrors(p.players, p.deathEvents, layout));
      }
    },
  },

  'graven2-strategy': {
    game: 'ff',
    load: () => requireTsFromRoot('lib/mechanics/ffxiv/dancingmad/graven2-strategy.ts'),
    run({ mod, ctxs }) {
      // Per-pull only (no cross-pull learning, no PullError output — see
      // module header) — just prints what each pull's own Gravitas hits
      // resolve to, for manual eyeballing. Doesn't participate in
      // --check/--update snapshot diffing since it emits no PullError[].
      console.log('-'.repeat(70));
      for (const c of ctxs) {
        const result = mod.detectGraven2Strategy(c.relPlayers());
        if (!result) {
          console.log(`  ${c.bossName} Pull ${c.pullNumber} -> Graven 2 not reached`);
        } else {
          const groups = result.groups.map((g) => `[${g.players.join(', ')}]`).join(' vs ');
          console.log(`  ${c.bossName} Pull ${c.pullNumber} -> Graven 2 variant: ${result.variant} (${groups})`);
        }
      }
    },
  },

  midnightfalls: {
    game: 'wow',
    load: () => ({
      ...requireTsFromRoot('lib/mechanics/wow/vs-dr-mqd/midnightfalls.ts'),
      ...requireTsFromRoot('lib/mechanics/wow/vs-dr-mqd/terminate-kicks.ts'),
      ...requireTsFromRoot('lib/mechanics/wow/vs-dr-mqd/crystal-assignments.ts'),
      ...requireTsFromRoot('lib/spec-data.ts'),
    }),
    run({ mod, pulls, actorMap, abilityMap }) {
      const builtPulls = [];
      for (const pull of pulls) {
        const { bossName, pullNumber } = pull;
        const { players, deaths, enemyCasts, enemyBuffs, friendlyNpcDamage } = wowPullContext(pull, actorMap, abilityMap, mod.getSpecInfo);
        builtPulls.push({ players });
        const errors = mod.detectMidnightFallsErrors(players, deaths, enemyCasts, enemyBuffs, friendlyNpcDamage);
        console.log('='.repeat(70));
        console.log(`${bossName} Pull ${pullNumber} ->`, errors.length, 'errors');
        for (const e of errors) {
          console.log(`  [${e.severity}] [${e.ruleId}] t=+${(e.timestamp / 1000).toFixed(1)}s ${e.player ?? '(raid)'}: ${e.name}`);
          // These rules put their real payload in the description (Light's
          // End source attribution, crystal healer breakdown, Terminate
          // no-hit downgrade) — print it so regressions are visible.
          if (['wow-raid-lights-end', 'wow-raid-dusk-crystal-unhealed', 'wow-raid-terminate-cast',
               'wow-mf-radiance', 'wow-mf-accidental-crystal-pickup'].includes(e.ruleId)) {
            console.log(`      ${e.description}`);
          }
        }
        recordErrors(bossName, pullNumber, errors);
      }

      // Report-level Terminate kick-order detection (feeds the Strategy dialog).
      const strategy = mod.detectTerminateKickOrder(builtPulls);
      console.log('='.repeat(70));
      if (!strategy) {
        console.log('Terminate kick order: no interrupt data detected');
      } else {
        console.log(`Terminate kick order (${strategy.pullsAnalyzed} pulls, ${strategy.wavesAnalyzed} waves):`);
        if (strategy.chains) {
          for (const chain of strategy.chains) {
            console.log(`  ${chain.label}: ${chain.slots.map((s) => `${s.player} (${s.ability})`).join(' -> ')}`);
          }
        } else {
          console.log('  (declared boss-frame chains did NOT validate against detection — showing raw rounds)');
          strategy.rounds.forEach((round, i) => {
            console.log(`  Round ${i + 1}: ${round.map((s) => `${s.player} (${s.ability})`).join(' / ')}`);
          });
        }
        if (strategy.fillIns.length) {
          console.log(`  Fill-ins: ${strategy.fillIns.map((s) => `${s.player} (${s.ability}, ${s.wavesSeen}/${strategy.wavesAnalyzed} waves)`).join(', ')}`);
        }
      }

      // Report-level Dawn Crystal assignment detection (feeds the Strategy dialog).
      const crystals = mod.detectCrystalAssignments(builtPulls);
      console.log('='.repeat(70));
      if (!crystals) {
        console.log('Crystal assignments: no Glimmering data detected');
      } else {
        console.log(`Dawn Crystal assignments (${crystals.pullsAnalyzed} pulls, declared match: ${crystals.matchesDeclared}):`);
        console.log(`  Set 1: ${crystals.set1.map((s) => `${s.player} (${s.pullsSeen})`).join(', ')}`);
        console.log(`  Set 2: ${crystals.set2.map((s) => `${s.player} (${s.pullsSeen})`).join(', ')}`);
        for (const swap of crystals.swaps) {
          console.log(`  Intermission: ${swap.from.player} -> ${swap.to.player} (${swap.pullsSeen} pulls)`);
        }
      }
    },
  },

  // The other per-pull WoW modules get generated entries from
  // lib/mechanics/wow/registry.ts (see addWowRegistryEntries below).

};

// Print-only (no PullErrors, nothing snapshotted): the new mitigation
// analysis (lib/mitigation/analyze.ts) for every pull, one line per raidwide
// hit plus its active mitigations, free ones and droppable set.
// docs/mitigation-redesign.md describes the columns.
MECHANICS['mitigation-analysis'] = {
  game: 'ff',
  load: () => ({
    store: requireTsFromRoot('lib/sample-report-store.ts'),
    lt: requireTsFromRoot('lib/log-transforms.ts', { './log-auth': {} }),
    ...requireTsFromRoot('lib/mitigation/analyze.ts'),
    ...requireTsFromRoot('lib/mitigation/aggregate.ts'),
    ...requireTsFromRoot('lib/mitigation/ffxiv-catalog.ts'),
  }),
  async run({ mod, dir }) {
    const pulls = await loadThroughRealPipeline(mod, dir);
    if (!pulls) return;
    const pctOf = (x) => `${Math.round(x * 100)}%`;
    const perPull = [];
    for (const pull of pulls) {
      const hits = mod.analyzePullMitigation(pull, mod.FFXIV_MITIGATION);
      perPull.push({ pullId: pull.id, pullNumber: pull.pullNumber, hits });
      const targets = hits.flatMap((h) => h.targets);
      const withMult = targets.filter((t) => t.multiplier !== undefined);
      console.log('='.repeat(70));
      console.log(`${pull.name} Pull ${pull.pullNumber}: ${hits.length} raidwide hits, catalog matches multiplier on ` +
        `${withMult.filter((t) => t.consistent).length}/${withMult.length} targets`);
      for (const h of hits) {
        const active = h.active.map((a) => `${a.name}${a.casters.length ? `(${a.casters.map((c) => c.split(' ')[0]).join('/')})` : ''}`).join(', ');
        const free = h.players.filter((p) => p.state === 'free').map((p) => `${p.name}(${p.player.split(' ')[0]})`).join(', ');
        const ineff = h.players.filter((p) => p.state === 'ineffective').map((p) => `${p.name}(${p.player.split(' ')[0]})`).join(', ');
        const deathInfo = h.targets.filter((t) => t.died).map((t) => `${t.player.split(' ')[0]}:${t.deathCause}`).join(' ');
        console.log(`  [${(h.timestampMs / 1000).toFixed(1)}s] seq${h.sequenceId} ${h.abilityName} #${h.occurrence} (${h.phase ?? '-'}, ${h.damageColumn ?? '?'}) ` +
          `n=${h.targets.length} margin=${pctOf(h.margin)} seq=${pctOf(h.sequenceMargin)} ${h.verdict.toUpperCase()}` +
          `${h.deaths ? ` deaths=${h.deaths} [${deathInfo}]` : ''}`);
        console.log(`      active: ${active || '-'}`);
        if (free) console.log(`      free: ${free}`);
        if (ineff) console.log(`      ineffective: ${ineff}`);
        if (h.droppable.keys.length) console.log(`      droppable: ${h.droppable.names.join(', ')} -> lowest ${pctOf(h.droppable.worstMargin)}`);
      }
    }
    console.log('='.repeat(70));
    console.log(`ALL PULLS (${perPull.length}): hits seen in 2+ pulls`);
    for (const a of mod.aggregateMitigation(perPull, mod.FFXIV_MITIGATION)) {
      if (a.pulls < 2) continue;
      const usual = a.active.filter((m) => m.pulls * 2 >= a.pulls).map((m) => m.name).join(', ');
      const free = a.free.filter((f) => f.pulls * 2 >= a.pulls).map((f) => `${f.name}(${f.player.split(' ')[0]})`).join(', ');
      console.log(`  ${(a.medianMs / 1000).toFixed(0).padStart(4)}s ${a.phase ?? '-'} | ${a.abilityName} #${a.occurrence} pulls=${a.pulls} ` +
        `median=${pctOf(a.medianMargin)} worst=${pctOf(a.worstMargin)} ${a.verdict.toUpperCase()}` +
        `${a.deaths ? ` deaths=${a.deaths} in ${a.deathPulls} pull(s)` : ''}`);
      console.log(`      usual: ${usual || '-'}`);
      if (free) console.log(`      usually free: ${free}`);
      if (a.droppable.keys.length) console.log(`      droppable (worst pull): ${a.droppable.names.join(', ')} -> lowest ${pctOf(a.droppable.worstMargin)}`);
    }
  },
};

// Print-only (no PullErrors, nothing snapshotted yet): the damage analysis
// (lib/damage/analyze.ts) for every pull: phase summary, then each player's
// estimated loss and top findings. `--all-findings` prints every finding.
// docs/damage-analysis-plan.md describes the model.
MECHANICS['damage-analysis'] = {
  game: 'ff',
  load: () => ({
    store: requireTsFromRoot('lib/sample-report-store.ts'),
    lt: requireTsFromRoot('lib/log-transforms.ts', { './log-auth': {} }),
    ...requireTsFromRoot('lib/damage/analyze.ts'),
    ...requireTsFromRoot('lib/damage/contexts.ts'),
    ...requireTsFromRoot('lib/damage/ffxiv/game.ts'),
  }),
  async run({ mod, dir }) {
    const pulls = await loadThroughRealPipeline(mod, dir);
    if (!pulls) return;
    const all = process.argv.includes('--all-findings');
    const M = (n) => (Math.abs(n) >= 1e6 ? `${(n / 1e6).toFixed(2)}M` : `${Math.round(n / 1000)}k`);
    const t = (ms) => `${(ms / 1000).toFixed(1)}s`;
    for (const pull of pulls) {
      const a = mod.analyzePullDamage(pull, mod.FFXIV_DAMAGE, mod.getDamageContext(pull.name));
      console.log('='.repeat(70));
      console.log(`${pull.name} Pull ${pull.pullNumber} (${pull.result}): analysed to ${t(a.endMs)}` +
        `${a.collapseMs !== undefined ? ' (wipe collapse)' : ''}, context ${a.context ?? 'MISSING'}` +
        `${a.missingData.length ? `, missing: ${a.missingData.join('; ')}` : ''}`);
      for (const ph of a.phases) {
        console.log(`  ${ph.name.padEnd(24)} ${t(ph.startMs).padStart(7)}-${t(ph.endMs).padEnd(7)} raid ${M(ph.raidDamage).padStart(7)}` +
          ` lost ${M(ph.raidLostDamage).padStart(6)}${ph.context?.decidesEnrage ? ' DECIDES ENRAGE' : ''}` +
          `${ph.bossHpLeft !== undefined ? ` boss HP left ${M(ph.bossHpLeft)}` : ''}`);
      }
      for (const p of a.players) {
        console.log(`  ${p.job.padEnd(12)} ${p.player.padEnd(18)} dealt ${M(p.damage).padStart(7)} lost ${M(p.lostDamage).padStart(6)}` +
          ` (forced ${M(p.forcedDamage)}) GCD ${t(p.baseGcdMs)} x${p.gcds}, in buffs ${p.buffWindowGcds.used}/${p.buffWindowGcds.fit}` +
          `, buffs given ${p.buffs.approximate ? '~' : ''}${M(p.buffs.given)} received ${M(p.buffs.received)}` +
          `${p.gcdSplit.heal ? `, heal GCDs ${p.gcdSplit.heal}/${p.gcdSplit.heal + p.gcdSplit.damage}` : ''}`);
        const shown = all ? p.findings : p.findings.filter((f) => !f.forced).slice(0, 4);
        for (const f of shown) {
          console.log(`      ${f.forced ? '(forced) ' : ''}${f.kind} ${t(f.startMs)} ${f.phase ?? ''}: ${M(f.lostDamage)} — ${f.detail}` +
            `${f.cause ? ` [${f.cause}]` : ''}${all ? `\n          basis: ${f.basis}` : ''}`);
        }
      }
    }
  },
};

// Print-only: the reference-clear comparison (lib/damage/compare.ts) of
// every pull in the folder that reached the deciding phase, against the
// clears named with --refs=<code>[,<code>...] (sample folders under
// sampledata/ff/). Equal windows from the start of that phase.
MECHANICS['damage-compare'] = {
  game: 'ff',
  load: () => ({
    store: requireTsFromRoot('lib/sample-report-store.ts'),
    lt: requireTsFromRoot('lib/log-transforms.ts', { './log-auth': {} }),
    ...requireTsFromRoot('lib/damage/analyze.ts'),
    ...requireTsFromRoot('lib/damage/compare.ts'),
    ...requireTsFromRoot('lib/damage/contexts.ts'),
    ...requireTsFromRoot('lib/damage/ffxiv/game.ts'),
  }),
  async run({ mod, dir }) {
    const refArg = process.argv.find((a) => a.startsWith('--refs='))?.slice('--refs='.length);
    if (!refArg) { console.log('  (needs --refs=<code>[,<code>...])'); return; }
    const toLogs = async (pulls, label) => pulls.map((pull) => ({
      pull, analysis: mod.analyzePullDamage(pull, mod.FFXIV_DAMAGE, mod.getDamageContext(pull.name)),
      label: `${label} #${pull.fightId}`,
    }));
    const refs = [];
    for (const code of refArg.split(',')) {
      const pulls = await loadThroughRealPipeline(mod, path.join(path.dirname(dir), code));
      refs.push(...(await toLogs((pulls ?? []).filter((p) => p.result === 'Kill'), code)));
    }
    const own = await toLogs(await loadThroughRealPipeline(mod, dir) ?? [], path.basename(dir));
    const ctx = mod.getDamageContext(own[0]?.pull.name ?? '');
    const k = (n) => (Number.isFinite(n) ? `${(n / 1000).toFixed(1)}k` : '-');
    const pct = (a, b) => (Number.isFinite(b) && b > 0 ? `${a >= b ? '+' : ''}${(((a - b) / b) * 100).toFixed(0)}%` : '');
    const show = (title, logs) => {
      const r = mod.compareWithReferences(logs, refs, mod.FFXIV_DAMAGE, ctx);
      console.log('='.repeat(70));
      if (r.error) { console.log(`${title}: ${r.error}`); return; }
      console.log(`${title}: ${r.phaseName}, first ${(r.windowMs / 1000).toFixed(0)}s, ${r.ownPulls} own pull(s) vs ${r.refs.length} clears`);
      console.log(`  raid DPS ${k(r.raid.dps)} vs ${k(r.raid.refDps)} ${pct(r.raid.dps, r.raid.refDps)}`);
      for (const ro of r.roles) console.log(`  ${ro.role.padEnd(7)} rDPS ${k(ro.rdps)} vs ${k(ro.refRdps)} ${pct(ro.rdps, ro.refRdps)}`);
      for (const p of r.rows) {
        console.log(`  ${p.job.padEnd(12)} ${p.player.padEnd(18)} rDPS ${k(p.rdps)} vs ${k(p.ref?.rdps)} ${pct(p.rdps, p.ref?.rdps)} (n=${p.refCount})` +
          ` own ${k(p.ownDps)}/${k(p.ref?.ownDps)} given ${k(p.givenDps)}/${k(p.ref?.givenDps)}` +
          ` GCD/min ${p.gcdsPerMin.toFixed(1)}/${(p.ref?.gcdsPerMin ?? NaN).toFixed(1)}` +
          `${p.healGcdsPerMin || p.ref?.healGcdsPerMin ? ` heal/min ${p.healGcdsPerMin.toFixed(1)}/${(p.ref?.healGcdsPerMin ?? NaN).toFixed(1)}` : ''}` +
          ` deaths ${p.deaths.toFixed(1)} est.loss ${k(p.lostDps)}/s`);
      }
    };
    for (const o of own) show(`${o.pull.name} Pull ${o.pull.pullNumber}`, [o]);
    show('ALL PULLS', own);
  },
};

// One generated entry per module in lib/mechanics/wow/registry.ts (except
// those with a hand-written entry above, marked customHarness there). A new
// WoW boss module needs no change here.
function addWowRegistryEntries() {
  const registry = requireTsFromRoot('lib/mechanics/wow/registry.ts');
  for (const m of registry.WOW_ENCOUNTER_MODULES) {
    if (m.customHarness || MECHANICS[m.name]) continue;
    MECHANICS[m.name] = {
      game: 'wow',
      load: () => requireTsFromRoot('lib/spec-data.ts'),
      run({ mod, pulls, actorMap, abilityMap }) {
        for (const pull of pulls) {
          const errors = m.detect(wowPullContext(pull, actorMap, abilityMap, mod.getSpecInfo));
          console.log('='.repeat(70));
          console.log(`${pull.bossName} Pull ${pull.pullNumber} ->`, errors.length, 'errors');
          for (const e of errors) {
            console.log(`  [${e.severity}] [${e.ruleId}] t=+${(e.timestamp / 1000).toFixed(1)}s ${e.player ?? '(raid)'}: ${e.description}`);
          }
          recordErrors(pull.bossName, pull.pullNumber, errors);
        }
      },
    };
  }
}
addWowRegistryEntries();

// Shared by the two mitigation entries: resolve the report folder to a code,
// load it through the app's own sample-report-store, and transform it with
// the real transformFFReportToPulls. Returns null (with a note) for folders
// the store can't see (i.e. anything outside sampledata/ff/<code>/).
async function loadThroughRealPipeline(mod, dir) {
  const code = path.basename(dir);
  if (!(await mod.store.sampleReportExists('ffl', code))) {
    console.log(`  (skipped: sample-report-store can't load '${code}' — mitigation checks only run on sampledata/ff/<code> folders)`);
    return null;
  }
  const payload = await mod.store.loadSampleReport('ffl', code);
  if (payload.source !== 'ffl') return null;
  const abilityMap = mod.lt.buildFFLAbilityMap(payload.report.masterData.abilities);
  return mod.lt.transformFFReportToPulls(payload.fightDataList, abilityMap, code);
}

// ── expectations: snapshots + rulings ───────────────────────────────────────

const EXPECTATIONS_DIR = path.join(ROOT, 'expectations');
const RULINGS_PATH = path.join(EXPECTATIONS_DIR, 'rulings.json');

function snapshotPath(game, code) {
  return path.join(EXPECTATIONS_DIR, `${game}-${code}.json`);
}

function readSnapshot(game, code) {
  const p = snapshotPath(game, code);
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

// --update: replace the snapshot's entries for the mechanics that ran,
// keeping entries of mechanics that didn't (so narrowed runs don't wipe the
// rest of the file).
// True when every pull's damage stream starts 5+ minutes after its
// combatantinfo events (the pull start) — a `fetch-ff-report.js
// --from-minutes` capture. Detected from the data so captures never need
// hand-editing.
function isLateCapture(pulls) {
  const LATE_MS = 5 * 60000;
  return pulls.length > 0 && pulls.every((p) => {
    const start = Math.min(...(p.rep.combatantInfo?.data ?? []).map((e) => e.timestamp));
    const firstHit = (p.rep.damageTaken?.data ?? [])[0]?.timestamp;
    return Number.isFinite(start) && firstHit !== undefined && firstHit - start >= LATE_MS;
  });
}

function writeSnapshot(game, code, mechsRun, entries) {
  const existing = readSnapshot(game, code);
  const kept = (existing?.errors ?? []).filter((e) => !mechsRun.includes(e.mechanic));
  const merged = sortEntries([...kept, ...entries]);
  fs.mkdirSync(EXPECTATIONS_DIR, { recursive: true });
  fs.writeFileSync(snapshotPath(game, code), JSON.stringify({ report: code, game, errors: merged }, null, 1) + '\n');
  console.log(`  wrote expectations/${game}-${code}.json (${merged.length} entries${kept.length ? `, ${kept.length} kept from mechanics not run` : ''})`);
}

// Multiset diff of baseline vs actual, then pair up removed+added entries
// that share an identity (mechanic/boss/pull/ruleId/player) so an
// intentional change (e.g. a severity downgrade, a reworded description)
// reads as one "~ changed" line with the differing fields, not an opaque
// remove+add pair.
function diffEntries(baseline, actual) {
  const key = (e) => JSON.stringify(e);
  const counts = new Map();
  for (const e of baseline) counts.set(key(e), (counts.get(key(e)) ?? 0) + 1);
  const added = [];
  for (const e of actual) {
    const k = key(e);
    if ((counts.get(k) ?? 0) > 0) counts.set(k, counts.get(k) - 1);
    else added.push(e);
  }
  const removed = [];
  const emitted = new Map();
  for (const e of baseline) {
    const k = key(e);
    if ((emitted.get(k) ?? 0) < (counts.get(k) ?? 0)) {
      removed.push(e);
      emitted.set(k, (emitted.get(k) ?? 0) + 1);
    }
  }

  const identity = (e) => [e.mechanic, e.boss, e.pull, e.ruleId, e.player].join('|');
  const removedByIdentity = new Map();
  for (const e of removed) {
    const id = identity(e);
    if (!removedByIdentity.has(id)) removedByIdentity.set(id, []);
    removedByIdentity.get(id).push(e);
  }
  const changed = [];
  const pureAdded = [];
  for (const e of added) {
    const pool = removedByIdentity.get(identity(e));
    if (pool && pool.length) changed.push({ before: pool.shift(), after: e });
    else pureAdded.push(e);
  }
  const pureRemoved = [...removedByIdentity.values()].flat();
  return { added: pureAdded, removed: pureRemoved, changed };
}

const clip = (s, n = 90) => (s && s.length > n ? s.slice(0, n) + '…' : s);

function describeEntry(e) {
  return `${e.mechanic} ${e.boss} Pull ${e.pull} [${e.ruleId}] t=${e.t} ${e.player ?? '(raid)'}: ${clip(e.description ?? e.name ?? '')}`;
}

function printDiff(diff) {
  for (const e of diff.removed) console.log(`  - ${describeEntry(e)}`);
  for (const e of diff.added) console.log(`  + ${describeEntry(e)}`);
  for (const { before, after } of diff.changed) {
    const fields = ['severity', 't', 'name', 'description'].filter((f) => before[f] !== after[f]);
    const detail = fields.map((f) => `${f}: ${clip(String(before[f]), 60)} -> ${clip(String(after[f]), 60)}`).join('; ');
    console.log(`  ~ ${before.mechanic} ${before.boss} Pull ${before.pull} [${before.ruleId}] ${before.player ?? '(raid)'} — ${detail}`);
  }
}

// Rulings (expectations/rulings.json): hand-curated adjudications from VOD
// review, checked on every --check run and NEVER regenerated by --update.
// Each ruling: { report, mechanic?, boss?, pull?, mustFlag: [...],
// mustNotFlag: [...], note?, date? } — mustFlag/mustNotFlag items match an
// entry when every field they specify (ruleId, player, severity, ...)
// equals the entry's; the ruling's own report/mechanic/boss/pull scope the
// candidate entries first.
function loadRulings() {
  if (!fs.existsSync(RULINGS_PATH)) return [];
  return JSON.parse(fs.readFileSync(RULINGS_PATH, 'utf8')).rulings ?? [];
}

function checkRulings(rulings, code, mechsRun, entries) {
  const violations = [];
  for (const r of rulings) {
    if (r.report !== code) continue;
    if (r.mechanic && !mechsRun.includes(r.mechanic)) continue; // narrowed run didn't exercise it
    const scoped = entries.filter((e) =>
      (r.mechanic === undefined || e.mechanic === r.mechanic) &&
      (r.boss === undefined || e.boss === r.boss) &&
      (r.pull === undefined || e.pull === r.pull));
    const matches = (spec) => scoped.filter((e) => Object.entries(spec).every(([f, v]) => e[f] === v));
    for (const spec of r.mustFlag ?? []) {
      if (matches(spec).length === 0) violations.push({ ruling: r, kind: 'mustFlag', spec });
    }
    for (const spec of r.mustNotFlag ?? []) {
      for (const e of matches(spec)) violations.push({ ruling: r, kind: 'mustNotFlag', spec, entry: e });
    }
  }
  return violations;
}

// Snapshots (and rulings) for reports whose sampledata folder has been
// deleted are unverifiable — detection can't re-run against them, so they
// can never fail again. --check/--update warn about them; --prune removes
// orphaned snapshots (rulings are hand-curated, so orphaned ones are only
// LISTED for hand-removal — their lesson may still need distilling into a
// module comment first).
function findOrphanSnapshots() {
  if (!fs.existsSync(EXPECTATIONS_DIR)) return [];
  const orphans = [];
  for (const f of fs.readdirSync(EXPECTATIONS_DIR)) {
    const m = f.match(/^(ff|wow)-(.+)\.json$/);
    if (!m) continue;
    if (!fs.existsSync(path.join(ROOT, 'sampledata', m[1], m[2]))) {
      orphans.push({ file: path.join(EXPECTATIONS_DIR, f), name: f, game: m[1], code: m[2] });
    }
  }
  return orphans;
}

function findOrphanRulings() {
  return loadRulings().filter((r) =>
    !fs.existsSync(path.join(ROOT, 'sampledata', 'ff', r.report)) &&
    !fs.existsSync(path.join(ROOT, 'sampledata', 'wow', r.report)));
}

function reportOrphans({ prune }) {
  const orphans = findOrphanSnapshots();
  const orphanRulings = findOrphanRulings();
  if (orphans.length === 0 && orphanRulings.length === 0) {
    if (prune) console.log('No orphaned snapshots or rulings — every expectations entry has its sampledata.');
    return;
  }
  console.log('#'.repeat(70));
  for (const o of orphans) {
    if (prune) {
      fs.unlinkSync(o.file);
      console.log(`PRUNED expectations/${o.name} (sampledata/${o.game}/${o.code}/ no longer exists)`);
    } else {
      console.log(`ORPHANED SNAPSHOT expectations/${o.name} — sampledata/${o.game}/${o.code}/ is gone; run --prune to remove`);
    }
  }
  for (const r of orphanRulings) {
    console.log(`ORPHANED RULING for report ${r.report} (${r.note ?? 'no note'}) — sampledata deleted; ` +
      'hand-remove it from expectations/rulings.json once its lesson is encoded in the module/README');
  }
}

// ── CLI driver ──────────────────────────────────────────────────────────────

const rawArgs = process.argv.slice(2);
if (rawArgs.includes('--list') || rawArgs.includes('--help') || rawArgs.includes('-h')) {
  console.log('Usage: node scripts/validate.js [--check|--update] [mechanic ...] [reportDir ...]');
  console.log('Mechanics:', Object.keys(MECHANICS).join(', '));
  console.log('No mechanic args = all. No reportDir args = every folder under sampledata/{ff,wow}/.');
  console.log('--check  diff detection output against expectations/ (snapshots + rulings); nonzero exit on any difference');
  console.log('--update regenerate expectations/ snapshots from current output (rulings are never touched)');
  console.log('--prune  delete snapshots whose sampledata report folder no longer exists');
  process.exit(0);
}

if (rawArgs.includes('--prune')) {
  reportOrphans({ prune: true });
  process.exit(0);
}

const mode = rawArgs.includes('--check') ? 'check' : rawArgs.includes('--update') ? 'update' : 'run';
if (rawArgs.includes('--check') && rawArgs.includes('--update')) {
  console.error('--check and --update are mutually exclusive');
  process.exit(1);
}

const selectedNames = [];
const explicitDirs = [];
for (const a of rawArgs) {
  if (a.startsWith('--')) continue;
  if (MECHANICS[a]) selectedNames.push(a);
  else explicitDirs.push(path.resolve(a));
}
const selected = selectedNames.length ? selectedNames : Object.keys(MECHANICS);

// A report folder's game: from its sampledata/{ff,wow}/ path segment when
// present; folders elsewhere run against both games' mechanics (every
// detection self-gates on its mechanic's signatures, so the wrong game's
// modules just report nothing).
function gamesOfDir(dir) {
  const segs = dir.split(path.sep);
  if (segs.includes('ff')) return ['ff'];
  if (segs.includes('wow')) return ['wow'];
  return ['ff', 'wow'];
}

(async () => {
  const loadedMods = new Map(); // mechanic name -> load() result
  const modFor = (name) => {
    if (!loadedMods.has(name)) loadedMods.set(name, MECHANICS[name].load());
    return loadedMods.get(name);
  };
  const { getFFJobByName } = requireTsFromRoot('lib/ffl-job-data.ts');
  const rulings = mode === 'check' ? loadRulings() : [];
  const failures = []; // check mode: one line per report with differences

  for (const game of ['ff', 'wow']) {
    const mechs = selected.filter((n) => MECHANICS[n].game === game);
    if (mechs.length === 0) continue;

    const dirs = explicitDirs.length
      ? explicitDirs.filter((d) => gamesOfDir(d).includes(game))
      : discoverReportFolders(path.join(ROOT, 'sampledata', game));

    if (dirs.length === 0 && explicitDirs.length === 0) {
      console.log(`No report folders found under sampledata/${game}/ (looked for subdirectories containing meta.json).`);
      console.log(`Fetch one with: node scripts/fetch-${game}-report.js <reportCode>`);
      continue;
    }

    for (const dir of dirs) {
      const loaded = loadReportFolder(dir);
      if (!loaded) { console.log(`${dir} -> no meta.json, skipping`); continue; }
      const { meta, pulls } = loaded;
      const actorMap = buildActorMap(meta);
      const abilityMap = buildAbilityMap(meta);

      console.log('#'.repeat(70));
      console.log(`${meta.title ?? meta.code} (${dir})`);
      console.log(`  ${pulls.length} pull(s)`);

      // A capture fetched with --from-minutes has deaths from the pull start
      // but every other stream only from late in the pull. Early-phase
      // mechanics would misread it, so only `lateCapture` mechanics run.
      const late = game === 'ff' && isLateCapture(pulls);
      const dirMechs = late ? mechs.filter((n) => MECHANICS[n].lateCapture) : mechs;
      if (late) console.log(`  late-start capture: running only ${dirMechs.join(', ') || '(none)'}`);

      const ctxs = game === 'ff' ? pulls.map((p) => makeFFPullCtx(p, actorMap, abilityMap, getFFJobByName)) : null;

      currentEntries = [];
      for (const name of dirMechs) {
        console.log('~'.repeat(70));
        console.log(`~ mechanic: ${name}`);
        currentMechanic = name;
        await MECHANICS[name].run({ mod: modFor(name), dir, meta, pulls, ctxs, actorMap, abilityMap });
      }
      const entries = sortEntries(currentEntries);
      currentEntries = null;
      const code = meta.code ?? path.basename(dir);

      if (mode === 'update') {
        writeSnapshot(game, code, dirMechs, entries);
      } else if (mode === 'check') {
        console.log('~'.repeat(70));
        const snapshot = readSnapshot(game, code);
        if (!snapshot) {
          console.log(`CHECK ${game}-${code}: NO BASELINE — run \`node scripts/validate.js --update ${dir}\` to create one`);
          failures.push(`${game}-${code}: no baseline`);
        } else {
          // Narrowed runs only compare the mechanics that actually ran.
          const baseline = snapshot.errors.filter((e) => dirMechs.includes(e.mechanic));
          const diff = diffEntries(baseline, entries);
          const total = diff.added.length + diff.removed.length + diff.changed.length;
          if (total === 0) {
            console.log(`CHECK ${game}-${code}: OK (${entries.length} errors match baseline)`);
          } else {
            console.log(`CHECK ${game}-${code}: ${total} difference(s) vs baseline (+${diff.added.length} -${diff.removed.length} ~${diff.changed.length})`);
            printDiff(diff);
            failures.push(`${game}-${code}: ${total} snapshot difference(s)`);
          }
          const violations = checkRulings(rulings, code, dirMechs, entries);
          for (const v of violations) {
            const where = [v.ruling.mechanic, v.ruling.boss, v.ruling.pull !== undefined ? `Pull ${v.ruling.pull}` : null].filter(Boolean).join(' ');
            if (v.kind === 'mustFlag') {
              console.log(`  RULING VIOLATED (${where}): expected a flag matching ${JSON.stringify(v.spec)} — none found. Note: ${v.ruling.note ?? '(none)'}`);
            } else {
              console.log(`  RULING VIOLATED (${where}): ${describeEntry(v.entry)} must NOT flag. Note: ${v.ruling.note ?? '(none)'}`);
            }
            failures.push(`${game}-${code}: ruling violation (${v.kind})`);
          }
        }
      }
    }
  }

  if (mode === 'check' || mode === 'update') reportOrphans({ prune: false });

  if (mode === 'check') {
    console.log('#'.repeat(70));
    if (failures.length === 0) {
      console.log('CHECK PASSED — all reports match their baselines and rulings.');
    } else {
      console.log(`CHECK FAILED — ${failures.length} problem(s):`);
      for (const f of failures) console.log(`  ${f}`);
      console.log('If these differences are INTENDED (detection philosophy evolved), verify the diff above is');
      console.log('exactly the intended change, then run `node scripts/validate.js --update` and commit the');
      console.log('snapshot diff. Rulings in expectations/rulings.json must be edited by hand, never regenerated.');
      process.exitCode = 1;
    }
  }
})().catch((err) => { console.error(err); process.exit(1); });
