// app/api/transcript/[videoId]/route.ts
//
// Fetches a YouTube video's auto-caption transcript via youtube-transcript.ai,
// a free, keyless hosted service. There's no supported public API for this —
// captions.download in the official YouTube Data API requires OAuth as the
// video's owner, which we don't have for other players' uploads — and
// scraping YouTube's own timedtext endpoint directly no longer works: as of
// 2026 it requires a PoToken (proof-of-origin token) that can only be
// produced by running YouTube's BotGuard attestation JS, which is far more
// machinery than this feature warrants. youtube-transcript.ai handles that
// on their end; we just parse the markdown transcript they return.

import { NextRequest, NextResponse } from "next/server";

type TranscriptLine = {
  startMs: number;
  text:    string;
};

const HTML_ENTITIES: Record<string, string> = {
  "&amp;":  "&",
  "&lt;":   "<",
  "&gt;":   ">",
  "&quot;": "\"",
  "&#39;":  "'",
  "&nbsp;": " ",
};

function decodeHtmlEntities(text: string): string {
  return text.replace(/&(?:amp|lt|gt|quot|#39|nbsp);/g, (entity) => HTML_ENTITIES[entity] ?? entity);
}

// Auto-generated captions on YouTube livestreams/premieres are produced
// live: each caption cue re-states a rolling window of recent words as
// they get finalized, so the raw transcript is full of runs like
// "positive impact positive impact positive impact" or a whole sentence
// repeated 2-3 times in a row. This collapses any word-sequence that
// immediately repeats itself down to a single occurrence. Greedy/exact —
// it targets the dominant clean-repeat pattern rather than every fuzzy
// overlap (e.g. a repeat that also drops or shifts a word at the seam),
// which is enough to fix the ~2-3x inflation this causes without trying
// to perfectly reconstruct the original captioning.
function collapseRepeatedPhrases(text: string): string {
  const words = text.split(/\s+/).filter(Boolean);
  const out: string[] = [];
  let i = 0;

  while (i < words.length) {
    let collapsed = false;
    const maxWindow = Math.min(15, Math.floor((words.length - i) / 2));

    for (let w = maxWindow; w >= 1; w--) {
      let repeats = 1;
      while (
        i + (repeats + 1) * w <= words.length &&
        words.slice(i + (repeats - 1) * w, i + repeats * w).join(" ") ===
          words.slice(i + repeats * w, i + (repeats + 1) * w).join(" ")
      ) {
        repeats++;
      }
      if (repeats > 1) {
        out.push(...words.slice(i, i + w));
        i += repeats * w;
        collapsed = true;
        break;
      }
    }

    if (!collapsed) {
      out.push(words[i]);
      i++;
    }
  }

  return out.join(" ");
}

// Response body looks like:
//
//   # Transcript: <title>
//   ...metadata...
//
//   ## Transcript
//   [0:01] some text ♪ more text ♪
//
//   [0:31] more text...
//   ---
//   Generated by ...
//
// Timestamps are [m:ss] or [h:mm:ss]; each marker's text runs until the
// next marker (or the trailing "---" footer).
function parseTranscriptText(raw: string): TranscriptLine[] {
  const headingIndex = raw.indexOf("## Transcript");
  if (headingIndex === -1) return [];

  let body = raw.slice(headingIndex + "## Transcript".length);
  const footerIndex = body.lastIndexOf("\n---");
  if (footerIndex !== -1) body = body.slice(0, footerIndex);

  const markerPattern = /\[(\d+):(\d{2})(?::(\d{2}))?\]/g;
  const markers: { matchStart: number; afterBracket: number; startMs: number }[] = [];

  let match: RegExpExecArray | null;
  while ((match = markerPattern.exec(body)) !== null) {
    const [first, second, third] = [match[1], match[2], match[3]];
    const startMs = third !== undefined
      ? ((Number(first) * 60 + Number(second)) * 60 + Number(third)) * 1000
      : (Number(first) * 60 + Number(second)) * 1000;

    markers.push({ matchStart: match.index, afterBracket: match.index + match[0].length, startMs });
  }

  return markers
    .map((marker, i) => {
      const end = i + 1 < markers.length ? markers[i + 1].matchStart : body.length;
      const raw = body.slice(marker.afterBracket, end).replace(/\s+/g, " ").trim();
      const text = collapseRepeatedPhrases(decodeHtmlEntities(raw));
      return { startMs: marker.startMs, text };
    })
    .filter(line => line.text.length > 0);
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ videoId: string }> }
) {
  const { videoId } = await params;

  if (!videoId || !/^[\w-]{6,20}$/.test(videoId)) {
    return NextResponse.json({ error: "Invalid video id" }, { status: 400 });
  }

  let res: Response;
  try {
    res = await fetch(`https://youtube-transcript.ai/transcript/${videoId}.txt`);
  } catch {
    return NextResponse.json({ error: "Failed to reach transcript service" }, { status: 502 });
  }

  if (!res.ok) {
    return NextResponse.json({ error: "No captions available for this video" }, { status: 404 });
  }

  const raw = await res.text();
  const lines = parseTranscriptText(raw);

  if (lines.length === 0) {
    return NextResponse.json({ error: "No captions available for this video" }, { status: 404 });
  }

  return NextResponse.json({ videoId, lines });
}
